language: perl
perl:
        - "5.24.1"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpanm --quiet --installdeps --notest Gnome2::Vte
  - cpanm --quiet --installdeps --notest Devel::Cover
